name: Show variables

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Deployment target'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  display-variables:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_target }}
    steps:
    - name: Use variables
      run: |
        echo "Organization variable : ${{ vars.ORG_NAME }}"
        echo "Repository variable : ${{ vars.PLATFORM_VERSION }}"
        echo "Environment variable : ${{ vars.SERVICE_URL }}"
